### ISSUE TITLE
[Beginner] How do I stop Uncap?

### ISSUE THREAD

**Issue by ianpan870102** [susam/uncap#14]
Thank you for this package! As a new windows user, I'd like to know what's the suggested way to stop uncap.exe if I ever need to?
Any help would be appreciated, thanks in advance.

**Comment by susam** [comment]
See [README: Usage](https://github.com/susam/uncap/blob/a259b35/README.md#usage): point 10:

> Uncap runs without displaying a console by default. To terminate another instance of Uncap that may be running, use the `-k` or `--kill` option.
>
>     uncap -k
>
> The above command kills all other instances of Uncap that are running with or without a console.

I hope this helps.
