### ISSUE TITLE
Automatic run at Windows start-up?

### ISSUE THREAD

**Issue by ianpan870102** [susam/uncap#15]
Thank you for this package! This is the simple solution I needed.

Right now I'm putting uncap.exe under my Program Files in C Drive, and whenever I restart Windows I'll have to navigate to the exe file and click to start uncap in the background.
Is there a way to have uncap.exe automatically start running? I'm rather a new Windows user, apologies if this is a rather trivial question.

**Comment by lemero** [comment]
Hi Ian,
I found out this morning that uncap doesn't persist after restarting. I stuck a shortcut in here: C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Thing is, I don't use uncap for remapping the caps lock key; I do need that key as it is. I use it for remapping other keys. After a restart, my customizations are removed.
So I hit winkey+R and it remembers the last entered command (in my case,I use uncap to create media keys, I'm using an older keyboard: "uncap 0x79:0xAF 0x7B:0xB3 0x78:0xAE 0x14:0x14") and hit enter to re-set it as I like. Even if you typed something else in that field, there's a drop-down list with a few of the last things you entered there, and I also saved this snippet in a file.

@devs: I wonder if there's a way to have uncap run with my code automatically?

**Comment by eskoONE** [comment]
you could use windows scheduler and execute the command you are using on start of windows. make sure to use "logging in" instead of "at boot up" as a trigger, as i had issues with the latter trigger option.

**Comment by leogama** [comment]
> I found out this morning that uncap doesn't persist after restarting. I stuck a shortcut in here: `C:\Users%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`
> Thing is, I don't use uncap for remapping the caps lock key; I do need that key as it is. I use it for remapping other keys. After a restart, my customizations are removed.
> (...)
> devs: I wonder if there's a way to have uncap run with my code automatically?

@lemero, you can edit the options in the shortcut to append the arguments to `uncap.exe`. That is exactly what I do.

This should be appended to the documentation in the home page:
1. In the Windows Explorer address bar go to `%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`;
2. Here in the startup programs folder, create a shortcut to the `uncap.exe` file;
3. Right-click on the shortcut, click "Properties", then go to the "Shortcut" tab (this is usually the one shown by default);
4. In the "Target" field, add your custom modifications after the executable path, **outside the quotes**;
    - Example: `"C:\Program Files\Portable\uncap.exe" 0x1b:0x14`
5. In the "Run" field, select "Minimized".
6. Log out and log in again to test the setup —note that if you have many programs being launched at login, Uncap may not run immediately.

That's all, folks!

**Comment by ianyepan** [comment]
I believe the comments above are enough for anybody looking for help. Closing issue!
