### ISSUE TITLE
Question ⁉: How to permenately `uncap`, run at startup

### ISSUE THREAD

**Issue by MuhammadSawalhy** [susam/uncap#21]
I managed to swap my CAPS and ESC using these commands

```bash
uncap
uncap 0x1b:0x14
```

But when I restart Windows they aren't swapped anymore. How can I permanently swap these two keys? You may put this in the REAME.md. If it is already explained in the readme file I think you should make it more clear.

**Comment by susam** [comment]
Uncap does not swap keys permanently. This is by design. You can however make Uncap part of Windows startup, so that whenever the system starts, Uncap runs automatically. See issue #15 for a discussion about this.

**Comment by MuhammadSawalhy** [comment]
Ok, I will close this issue. I hope to add these instruction in the README file

https://github.com/susam/uncap/issues/15#issuecomment-727639874
